# Generated by Django 3.2 on 2021-04-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='current_intrest_rate',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='transactionintrestrate',
            name='set_intrest_rate',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
