# Generated by Django 3.2 on 2021-04-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20210420_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='current_payout_rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
