# Generated by Django 3.2 on 2021-04-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bank_current_payout_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='current_intrest_rate',
            new_name='interest_rate',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='current_payout_rate',
            new_name='payout_rate',
        ),
        migrations.RenameField(
            model_name='transactionintrestrate',
            old_name='set_intrest_rate',
            new_name='set_interest_rate',
        ),
    ]
