# Generated by Django 3.2 on 2021-04-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20210425_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionintrestrate',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
