# Generated by Django 3.2 on 2021-04-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_transactionintrestrate_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionintrestrate',
            name='end_date',
            field=models.TimeField(auto_now=True),
        ),
    ]
