# Generated by Django 3.2 on 2021-04-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_transactionintrestrate_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionintrestrate',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
