# Generated by Django 3.2 on 2021-04-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_alter_transactionintrestrate_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionintrestrate',
            name='end_date',
            field=models.DateField(),
        ),
    ]
