# Generated by Django 3.2 on 2021-04-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_alter_transactionintrestrate_end_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionIntrestRate',
            new_name='TransactionInterestRate',
        ),
    ]
