# Generated by Django 3.2 on 2021-04-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_rename_transactionintrestrate_transactioninterestrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='classroom',
            new_name='class_code',
        ),
    ]
