# Generated by Django 3.2 on 2021-04-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.IntegerField(),
        ),
    ]
