# Generated by Django 3.2 on 2021-04-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20210419_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='recipient',
            new_name='recipient_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sender',
            new_name='sender_id',
        ),
    ]
