# Generated by Django 3.2 on 2021-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='classroom',
            field=models.CharField(max_length=6),
        ),
    ]
