# Generated by Django 3.2 on 2021-04-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_shop_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shop',
            field=models.CharField(max_length=6),
        ),
    ]
