# Generated by Django 3.2 on 2021-04-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_item_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shop',
            field=models.IntegerField(),
        ),
    ]
