# Generated by Django 3.2 on 2021-04-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_item_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
