# Generated by Django 3.2 on 2021-04-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_boughtitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='classroom',
            new_name='class_code',
        ),
    ]
