# Generated by Django 3.2 on 2021-04-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_classroom_shop_class_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='shop',
            new_name='shop_id',
        ),
    ]
