# Generated by Django 3.2 on 2021-04-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('teacher_id', models.IntegerField()),
                ('class_code', models.CharField(max_length=6)),
            ],
        ),
    ]
